SSO_BASE_URL doesn't get replaced by app-interface
Just use the explicit domain for now.

```
File "/app-root/src/lightspeed_stack.py", line 91, in <module>
main()
File "/app-root/src/lightspeed_stack.py", line 67, in main
configuration.load_configuration(args.config_file)
File "/app-root/src/configuration.py", line 41, in load_configuration
self.init_from_dict(config_dict)
File "/app-root/src/configuration.py", line 45, in init_from_dict
self._configuration = Configuration(**config_dict)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app-root/.venv/lib64/python3.12/site-packages/pydantic/main.py", line 253, in __init__
validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Configuration
authentication.jwk_config.url
Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='${SSO_BASE_URL}/protocol/openid-connect/certs', input_type=str]
For further information visit https://errors.pydantic.dev/2.11/v/url_parsing
```